name: Notify Unimore Info

on:
  push:
    branches: [ main ]

jobs:
  send:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
    - name: Telegram Message Notify
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: -1001234297904
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        disable_web_page_preview: true
        message: |
          <a href="https://uni.steffo.eu">Appuntiweb</a> è stato aggiornato!

          ${{ github.event.head_commit.message }}
